# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZblog', '0002_auto_20170923_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminimg',
            name='img',
            field=models.ImageField(upload_to='./static/upload/img'),
        ),
    ]
