# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZblog', '0003_auto_20171003_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='tianqiForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chengshi', models.CharField(max_length=100, verbose_name='城市')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('img', models.CharField(max_length=200, verbose_name='图片')),
                ('temperature', models.CharField(max_length=30, verbose_name='温度')),
                ('cloud', models.CharField(max_length=20, verbose_name='云')),
                ('wind', models.CharField(max_length=20, verbose_name='风')),
            ],
        ),
    ]
