# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZblog', '0003_auto_20170923_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminimg',
            name='img',
            field=models.ImageField(upload_to='./admin'),
        ),
    ]
