# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZblog', '0004_auto_20170923_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='please fill a describe', max_length=200, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
