# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZblog', '0004_tianqiform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
